name: PHPCS

on:
  push:
    branches: ['1.x']
  pull_request:

jobs:
  phpcs:
    name: PHP_CodeSniffer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: pcntl
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        uses: ramsey/composer-install@v3

      - name: Run PHPCS
        run: vendor/bin/phpcs --standard=PSR12 src bin/solar-power-controller
